2025-03-11 12:00:17,462 - INFO - testing_goldens - testing_goldens.py:84 - Loaded total of 791 Chunks
2025-03-11 12:00:18,511 - INFO - testing_goldens - testing_goldens.py:251 - Testing Attack @ 2025-03-11 12:00:18.511830+08:00
2025-03-11 12:00:22,607 - ERROR - RagFlow - RagFlow.py:240 - Error at Target Model Callback: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000250A5E23E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-11 12:00:26,679 - ERROR - RagFlow - RagFlow.py:240 - Error at Target Model Callback: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000250A5E45B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-11 12:00:30,771 - ERROR - RagFlow - RagFlow.py:240 - Error at Target Model Callback: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000250A5E4C290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
